version: '3.1'

services:
  api:
    build: .
    container_name: node-essential
    ports:
      - 3333:3333
    environment:
      PORT: 3333
      NODE_ENV: production
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
